module.exports = {
  "ALIVE_IMG": "https://files.catbox.moe/vdheyh.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "94726884134",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "🍂🖤𝗞𝗜𝗡𝗚 𝗔𝗡𝗝𝗔𝗡𝗔 𝗕𝗕𝗛 💦🥵🍂",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "🗿"
};
